server:
  port: 80
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:bootystar/test/mapper/xml/*Mapper.xml
  mapper-base-package: bootystar.test.mapper
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    bootystar.test.mapper: debug
booty:
  minio:
    enable: true
    endpoint: http://192.168.56.104:9000
    bucket-name: zhangsan
    access-key: booty
    secret-key: bootystar

